config/routes.rb
Rails.application.routes.draw do

  get 'request_post_jobs/new'

  get 'volunteer_sessions/new'

  get 'volunteer_users/new'

  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/faq',   to: 'static_pages#faq'
  #get '/debugreview', to: 'static_pages#debugreview'
  #get '/debugrequestreview', to: 'static_pages#debugrequestreview'
  get '/reqsignup', to: 'request_users#new'
  resources :request_users do
    member do
      get :followers
    end
  end
  resources :user_scorecards
  resources :request_user_scorecards
  resources :volunteer_users do
    member do
      post 'signal_interest'
      get :following
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :notifications, only: [:show, :destroy]
  resources :request_posts
  resources :request_post_updates, only: [:create, :destroy]
  get '/notifications', to: 'notifications#show'
  resources :availabilities
  resources :request_post_jobs do
    member do
      post 'user_sig_interest'
      post 'assoc_with_user'
    end
  end
  get '/reqpostcreation', to: 'request_posts#new'
  get '/volusers', to: 'volunteer_users#index'
  get '/requsers', to: 'request_users#index'
  get '/reqposts', to: 'request_posts#index'
  get '/volreview', to: 'volunteer_users#score'
  get '/orgreview', to: 'request_users#score'
  get '/reqlogin', to: 'request_sessions#new'
  post '/reqlogin', to: 'request_sessions#create'
  delete '/reqlogout', to: 'request_sessions#destroy'
  get '/volsignup', to: 'volunteer_users#new'
  get '/vollogin', to: 'volunteer_sessions#new'
  post '/vollogin', to: 'volunteer_sessions#create'
  delete '/vollogout', to: 'volunteer_sessions#destroy'
  get '/newreqpost', to: 'request_posts#new'
  get '/newavailability', to: 'availabilities#new'
  get '/following', to: 'volunteer_users#following'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def faq
  end
  
  def debugreview
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>About Voluntr</h1>
<p>Voluntr is a website designed to connect skilled volunteers with the
organizations that need them. It was built by Rowan University students
in the fall of 2016.</p>

app/views/static_pages/debugrequestreview.html.erb
<div class="ReviewRequest">
    <h1>Test Request Review Page</h1>
    <p>
        <%= form_for RequestUserScorecard.find_by(request_user_id: '1') do |f| %>
            <%= f.label :request_user_id, "User Number" %>
                <%= f.text_field :request_user_id %>

                    <%= f.label :leadership, "Leadership" %>
                        <%= f.text_field :leadership %>

                            <%= f.label :treatment, "Treatment" %>
                                <%= f.text_field :treatment %>

                                    <%= f.label :committedness, "Committedness" %>
                                        <%= f.text_field :committedness %>

                                                    <%= f.submit "Confirm Review" %>
                                                        <% end %>
    </p>
</div>

app/views/static_pages/faq.html.erb
<h1>Frequently Asked Questions</h1>
<p>Questions will be added as soon as we figure out what they are.</p>
<h1>"What are the frequently asked questions?" - peteycrak</h1>

app/views/static_pages/home.html.erb
<center>
    <h1>
        Welcome to Voluntr!
    </h1>
</center>

<section class="container-section">
    <% if !(request_user_logged_in? || volunteer_user_logged_in?)  %>
    <p>
        <%= link_to "Looking for volunteers? Sign up here.", reqsignup_path %>
    </p>
    <p>
        <%= link_to "Interested in volunteering? Sign up here.", volsignup_path %>
    </p>
    <% end %>
    Some Recent Requests:
    <% for i in RequestPost.take(25) %>
        <div class="notification">
            <%= i.title %> ->
                <%= i.description.truncate(25, omission: "...") %>
                    <%= link_to "<click me!>", i %>
        </div>
    <% end %>
</section>