config/routes.rb
Rails.application.routes.draw do

  get 'request_post_jobs/new'

  get 'volunteer_sessions/new'

  get 'volunteer_users/new'

  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/faq',   to: 'static_pages#faq'
  #get '/debugreview', to: 'static_pages#debugreview'
  #get '/debugrequestreview', to: 'static_pages#debugrequestreview'
  get '/reqsignup', to: 'request_users#new'
  resources :request_users do
    member do
      get :followers
    end
  end
  resources :user_scorecards
  resources :request_user_scorecards
  resources :volunteer_users do
    member do
      post 'signal_interest'
      get :following
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :notifications, only: [:show, :destroy]
  resources :request_posts
  resources :request_post_updates, only: [:create, :destroy]
  get '/notifications', to: 'notifications#show'
  resources :availabilities
  resources :request_post_jobs do
    member do
      post 'user_sig_interest'
      post 'assoc_with_user'
    end
  end
  get '/reqpostcreation', to: 'request_posts#new'
  get '/volusers', to: 'volunteer_users#index'
  get '/requsers', to: 'request_users#index'
  get '/reqposts', to: 'request_posts#index'
  get '/volreview', to: 'volunteer_users#score'
  get '/orgreview', to: 'request_users#score'
  get '/reqlogin', to: 'request_sessions#new'
  post '/reqlogin', to: 'request_sessions#create'
  delete '/reqlogout', to: 'request_sessions#destroy'
  get '/volsignup', to: 'volunteer_users#new'
  get '/vollogin', to: 'volunteer_sessions#new'
  post '/vollogin', to: 'volunteer_sessions#create'
  delete '/vollogout', to: 'volunteer_sessions#destroy'
  get '/newreqpost', to: 'request_posts#new'
  get '/newavailability', to: 'availabilities#new'
  get '/following', to: 'volunteer_users#following'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/request_user.rb
class RequestUser < ApplicationRecord
  attr_accessor :remember_token 
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_URL_REGEX = /\A(https*:\/\/www\.\w*\.[a-z]{2,}\/?\S*)?\z/i
  
  has_many :request_posts, dependent: :destroy
  before_save {self.email = email.downcase}
  validates :display_name, presence: true, length: {maximum: 60}
  validates :email, presence: true, length: {maximum: 150},
                 format: {with: VALID_EMAIL_REGEX},
                 uniqueness: {case_sensitive: false}
  validates :website_address, format: {with: VALID_URL_REGEX}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  has_one :request_user_scorecard
  has_many :notifications, :as => :user
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_attached_file :logo, :styles => { :small => "150x150>" }
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
  
  def RequestUser.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = RequestUser.new_token
    update_attribute(:remember_digest, RequestUser.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def RequestUser.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def self.search(search)
    if search
      search.downcase!
        #all.select{|x| x.display_name.downcase! == search}
        where("LOWER(display_name) LIKE ? or LOWER(email) LIKE ?", "%#{search}%", "%#{search}%")
    else
      all
    end
  end    
    
    
    
end

app/controllers/request_users_controller.rb
class RequestUsersController < ApplicationController
  def new
    @request_user = RequestUser.new
  end
  
  def index
    #@request_users = RequestUser.all
    @request_users = RequestUser.search(params[:search])
  end
  
  def create 
    @request_user = RequestUser.new(request_user_params)
    ##Initialize Scorecard
    @request_user.request_user_scorecard = RequestUserScorecard.new
    @request_user.build_request_user_scorecard( request_user_id: @request_user_id, 
                leadership: 0,treatment: 0,committedness: 0)
    @request_user.rev_count = 0
    if @request_user.save
      request_log_in @request_user
      flash[:success] = "Log in successful"
      redirect_to @request_user
    else
      render 'new'
    end
  end
  
  def update
    @request_user = RequestUser.find(params[:id])
    if @request_user.update_attributes(request_user_params)
      @request_user = request_user_params
      redirect_to @request_user
    else
      render 'edit'
    end
  end

  def edit
    @request_user = RequestUser.find(params[:id])
    if !requesters_id_is(@request_user.id)
      redirect_to root_url
    end
  end
  
  def show
    @request_user = RequestUser.find(params[:id])
  end
  
  private
    def request_user_params
      params.require(:request_user).permit(:email, :display_name, :tel_num,
        :fax_num, :website_address, :about_me, :password, :password_confirmation, :logo)
    end
    
    
end

app/helpers/request_users_helper.rb
module RequestUsersHelper
end

app/views/request_users/_follow.html.erb
<%= form_for(current_volunteer_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @request_user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/request_users/_follow_form.html.erb
<!--<%# unless current_user?(@user) %>
  -->
<div id="follow_form">

        <% if current_volunteer_user.following?(@request_user) %>
            <%= render 'unfollow' %>
                <% else %>
                    <%= render 'follow' %>
                        <% end %>
</div>

app/views/request_users/_unfollow.html.erb
<%= form_for(current_volunteer_user.active_relationships.find_by(followed_id: @request_user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/request_users/edit.html.erb
<% provide(:title, "Edit Organization") %>
  <h1>Update your profile</h1>

  <section class="container-section">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @request_user, html: { multipart: true } do |f| %>
        <%= render 'shared/req_error_messages' %>


          <%= f.label :logo, "Logo" %>
            <%= f.file_field :logo %>


              <%= f.label :email %>
                <%= f.text_field :email, class: 'form-control' %>

                  <%= f.label :display_name, "Display Name" %>
                    <%= f.text_field :display_name, class: 'form-control' %>

                      <%= f.label :tel_num, "Telephone Number" %>
                        <%= f.text_field :tel_num, class: 'form-control' %>

                          <%= f.label :fax_num, "Fax Number" %>
                            <%= f.text_field :fax_num, class: 'form-control' %>

                              <%= f.label :website_address, "Website" %>
                                <%= f.text_field :website_address, class: 'form-control' %>

                                  <%= f.label :about_me, "About Me" %>
                                    <%= f.text_area :about_me, class: 'form-control' %>

                                      <%= f.label :password %>
                                        <%= f.password_field :password, class: 'form-control' %>

                                          <%= f.label :password_confirmation, "Confirm" %>
                                            <%= f.password_field :password_confirmation, class: 'form-control' %>

                                              <%= f.submit "Save changes", class: "btn btn-primary" %>
                                                <% end %>

    </div>
  </div>
  </section>

app/views/request_users/index.html.erb
<head>
<style>
input[type=text] {
    width: 130px;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 4px;
    font-size: 16px;
    background-color: white;
    background-image: url('/assets/searchicon.png');
    background-position: 10px 10px;
    background-repeat: no-repeat;
    padding: 12px 20px 12px 40px;
    -webkit-transition: width 0.4s ease-in-out;
    transition: width 0.4s ease-in-out;
}

input[type=text]:focus {
    width: 100%;
}
</style>
</head>

<% provide(:title, 'Seach users') %>
  <h1>Search for an Organization</h1>

  <section class="container-section">

    <%= form_tag requsers_path, :method => 'get' do %>
      <p>
        <%= text_field_tag :search, params[:search] %><br>
          <%= submit_tag "Search", :name => nil %>
      </p>
      <% end %>

        <ul class="request_users">
          <% @request_users.each do |user| %>
            <li>
              <%= link_to user.display_name, user %>
            </li>
            <% end %>
        </ul>
  </section>

app/views/request_users/new.html.erb
<h1>Organization Sign Up</h1>
<section class= "container-section">
<p1>
  <%= link_to "Already have an account? Sign in here", reqlogin_path %>
</p1>
<p>
  <%= form_for @request_user, html: { multipart: true } do |f| %>
    <%= render 'shared/req_error_messages' %>

      <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>

          <%= f.label :display_name, "Display Name" %>
            <%= f.text_field :display_name, class: 'form-control' %>

              <%= f.label :tel_num, "Telephone Number" %>
                <%= f.text_field :tel_num, class: 'form-control' %>

                  <%= f.label :fax_num, "Fax Number" %>
                    <%= f.text_field :fax_num, class: 'form-control' %>

                      <%= f.label :website_address, "Website" %>
                        <%= f.text_field :website_address, class: 'form-control' %>

                          <%= f.label :about_me, "About Me" %>
                            <%= f.text_area :about_me, class: 'form-control' %>

                              <%= f.label :logo, "Logo" %>
                                <%= f.file_field :logo %>

                                  <%= f.label :password %>
                                    <%= f.password_field :password, class: 'form-control' %>

                                      <%= f.label :password_confirmation, "Confirm" %>
                                        <%= f.password_field :password_confirmation, class: 'form-control' %>

                                          <%= f.submit "Create account" %>

                                            <% end %>
</p>
</section>

app/views/request_users/score.html.erb
    <h1>Organization Review</h1>
    <section class = "container-section">
    <p>
        <%= form_for RequestUserScorecard.find(params[:request_user_id]) do |f| %>
            <%= f.hidden_field :request_user_id %>
            <%= hidden_field_tag(:rpjid, params[:rpjid]) %>
            
            <%= f.label :leadership, "Leadership" %>
            <%= f.text_field :leadership %><br>
            
            <%= f.label :treatment, "Treatment" %>
            <%= f.text_field :treatment %><br>
            
            <%= f.label :committedness, "Committedness" %>
            <%= f.text_field :committedness %><br>
            
            <%= f.submit "Confirm Review" %>
        <% end %>
    </p>
    </section>

app/views/request_users/show.html.erb
<h1>
    <%= image_tag @request_user.logo.url %>
        <%= @request_user.display_name %>
</h1>

                <% if volunteer_user_logged_in? %>
                <div class = "topcorner">
                    <p>
                        <%= render 'follow_form' %>
                    </p>
                <% end %>
                </div>

<div class="RequestInfo">

    <section class="container-section">

        <section class="section-left">

            <p>
                <%= render 'shared/req_stats' %>
            </p>

            <p>Email:
                <%= @request_user.email %>
            </p>
            <% if !@request_user.tel_num.empty? %>
                <p>Telephone Number:
                    <%= @request_user.tel_num %>
                </p>
                <% end %>
                    <% if !@request_user.fax_num.empty? %>
                        <p>Fax Number:
                            <%= @request_user.fax_num %>
                        </p>
                        <% end %>
        </section>

        <section class="section-right">

                    <h3>About Me</h3>
                    <p>
                        <%= @request_user.about_me %>
                            <p><br /></p>
                    </p>
                    <% if @request_user.website_address.empty? %>
                        <p>No Website</p>
                        <% else %>
                            <%= link_to "Website", @request_user.website_address %>
                                <% end %>
                                
        </section>

    </section>
</div>

<p><br /></p>
<p><br /></p>

<div class="OrganizationScore">
    <section class="container-section">

        <section class="section-left">
            <h3>Scorecard</h3>
                        <table class = "table-scorecard">
                <tr>
            <th>Leadership</th>
            <td>
                <%= @request_user.request_user_scorecard.leadership %>
            </td>
            </tr>
            <tr>
            <th>Treatmeant</th>
            <td>
                <%= @request_user.request_user_scorecard.treatment %>
            </td>
            </tr>
            <tr>
            <th>Committedness</th>
                <td>
               <%= @request_user.request_user_scorecard.committedness %>
            </td>
            </tr>
            <tr>
            <th>Times Reviewed</th>
            <td>
                <%= @request_user.rev_count %>
            </td>
            </tr>
            </table>
        </section>

        <section class="section-right">
            <h3>Recent Events</h3>

            <% for request_post in @request_user.request_posts.all.take(2) %>

                <div class="notification">
                    <h4>
                        <%= request_post.title %>
                    </h4>
                    <p><br /></p>
                    <%= request_post.description.truncate(120, omission: "...") %>
                        <p><br /></p>
                        <%= link_to "<click me!>", request_post %>
                </div>
                <% end %>
        </section>

    </section>
</div>