config/routes.rb
Rails.application.routes.draw do

  get 'request_post_jobs/new'

  get 'volunteer_sessions/new'

  get 'volunteer_users/new'

  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/faq',   to: 'static_pages#faq'
  #get '/debugreview', to: 'static_pages#debugreview'
  #get '/debugrequestreview', to: 'static_pages#debugrequestreview'
  get '/reqsignup', to: 'request_users#new'
  resources :request_users do
    member do
      get :followers
    end
  end
  resources :user_scorecards
  resources :request_user_scorecards
  resources :volunteer_users do
    member do
      post 'signal_interest'
      get :following
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :notifications, only: [:show, :destroy]
  resources :request_posts
  resources :request_post_updates, only: [:create, :destroy]
  get '/notifications', to: 'notifications#show'
  resources :availabilities
  resources :request_post_jobs do
    member do
      post 'user_sig_interest'
      post 'assoc_with_user'
    end
  end
  get '/reqpostcreation', to: 'request_posts#new'
  get '/volusers', to: 'volunteer_users#index'
  get '/requsers', to: 'request_users#index'
  get '/reqposts', to: 'request_posts#index'
  get '/volreview', to: 'volunteer_users#score'
  get '/orgreview', to: 'request_users#score'
  get '/reqlogin', to: 'request_sessions#new'
  post '/reqlogin', to: 'request_sessions#create'
  delete '/reqlogout', to: 'request_sessions#destroy'
  get '/volsignup', to: 'volunteer_users#new'
  get '/vollogin', to: 'volunteer_sessions#new'
  post '/vollogin', to: 'volunteer_sessions#create'
  delete '/vollogout', to: 'volunteer_sessions#destroy'
  get '/newreqpost', to: 'request_posts#new'
  get '/newavailability', to: 'availabilities#new'
  get '/following', to: 'volunteer_users#following'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/views/shared/_req_error_messages.html.erb
<% if @request_user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@request_user.errors.count, "error") %>.
    </div>
    <ul>
    <% @request_user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_req_stats.html.erb
<% @request_user ||= current_user %>
<div class="stats">
  <a href="<%= request_user_path %>">
    <strong id="followers" class="stat">
      <%= @request_user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_vol_error_messages.html.erb
<% if @volunteer_user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@volunteer_user.errors.count, "error") %>.
    </div>
    <ul>
    <% @volunteer_user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_vol_stats.html.erb
<% @volunteer_user ||= current_user %>
<div class="stats">
  <a href="<%= following_volunteer_user_path(@volunteer_user) %>">
    <strong id="following" class="stat">
      <%= @volunteer_user.following.count %>
    </strong>
    following
  </a>
</div>