config/routes.rb
Rails.application.routes.draw do

  get 'request_post_jobs/new'

  get 'volunteer_sessions/new'

  get 'volunteer_users/new'

  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/faq',   to: 'static_pages#faq'
  #get '/debugreview', to: 'static_pages#debugreview'
  #get '/debugrequestreview', to: 'static_pages#debugrequestreview'
  get '/reqsignup', to: 'request_users#new'
  resources :request_users do
    member do
      get :followers
    end
  end
  resources :user_scorecards
  resources :request_user_scorecards
  resources :volunteer_users do
    member do
      post 'signal_interest'
      get :following
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :notifications, only: [:show, :destroy]
  resources :request_posts
  resources :request_post_updates, only: [:create, :destroy]
  get '/notifications', to: 'notifications#show'
  resources :availabilities
  resources :request_post_jobs do
    member do
      post 'user_sig_interest'
      post 'assoc_with_user'
    end
  end
  get '/reqpostcreation', to: 'request_posts#new'
  get '/volusers', to: 'volunteer_users#index'
  get '/requsers', to: 'request_users#index'
  get '/reqposts', to: 'request_posts#index'
  get '/volreview', to: 'volunteer_users#score'
  get '/orgreview', to: 'request_users#score'
  get '/reqlogin', to: 'request_sessions#new'
  post '/reqlogin', to: 'request_sessions#create'
  delete '/reqlogout', to: 'request_sessions#destroy'
  get '/volsignup', to: 'volunteer_users#new'
  get '/vollogin', to: 'volunteer_sessions#new'
  post '/vollogin', to: 'volunteer_sessions#create'
  delete '/vollogout', to: 'volunteer_sessions#destroy'
  get '/newreqpost', to: 'request_posts#new'
  get '/newavailability', to: 'availabilities#new'
  get '/following', to: 'volunteer_users#following'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/volunteer_user.rb
class VolunteerUser < ApplicationRecord
  attr_accessor :remember_token
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_ZIP_REGEX = /\A\d{5}-\d{4}|\A\d{5}\z/
  
  before_save {self.email = email.downcase}
  validates :display_name, presence: true, length: {maximum: 60}
  validates :email, presence: true, length: {maximum: 150},
                 format: {with: VALID_EMAIL_REGEX},
                 uniqueness: {case_sensitive: false}
  validates :zip_code, presence: true, length: {maximum: 10},
                format: {with: VALID_ZIP_REGEX}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}, allow_nil: true
  has_one :availability
  has_one :user_scorecard
  has_many :skills
  has_many :notifications, :as => :user
  has_many :volunteer_user_skills, dependent: :destroy
  has_many :skills, through: :volunteer_user_skills
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_attached_file :avatar
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  
  def VolunteerUser.new_token
    SecureRandom.urlsafe_base64
  end
  
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :volunteer_user_id"
    RequestPost.where("volunteer_user_id IN (#{following_ids})
                     OR volunteer_user_id = :volunteer_user_id", volunteer_user_id: id)
  end

  def remember
    self.remember_token = VolunteerUser.new_token
    update_attribute(:remember_digest, VolunteerUser.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def VolunteerUser.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def self.search(search)
    if search
        search.downcase!
          
          first = joins(:skills).where("LOWER(skills.title) LIKE ?", "%#{search}%").group(:id)
          
          where("LOWER(display_name) LIKE ? or LOWER(email) LIKE ?", "%#{search}%", "%#{search}%").all + first.all
          
    else
      all
    end
  end

  
  def follow(other)
    active_relationships.create(followed_id: other.id)
  end
  
  def unfollow(other)
    active_relationships.find_by(followed_id: other.id).destroy
  end
  
  def following?(other)
    following.include?(other)
  end
  
  
end

app/controllers/volunteer_users_controller.rb
class VolunteerUsersController < ApplicationController
  
  def index
    #Redirect to home page if a volunteer user is not logged in
    if (!current_request_user)
      redirect_to root_url
    end
    
    #Search database for volunteer user matching search param
    @volunteer_users = VolunteerUser.search(params[:search])
    @volunteer_users = @volunteer_users.select{|x| !x.no_search}
  end
  
  def new
    #Create a new volunteer user record
    @volunteer_user = VolunteerUser.new
  end
  
  def create
    #Create a volunteer user with the passed params
    @volunteer_user = VolunteerUser.new(volunteer_user_params)
    #Create an empty scorecard for the volunteer user
    @volunteer_user.user_scorecard = UserScorecard.new
    @volunteer_user.build_user_scorecard(volunteer_user_id: @volunteer_user_id, 
                skill_proficiency: 0,attitude: 0,enthusiasm: 0, reliability: 0)
    @volunteer_user.build_availability(volunteer_user_id: @volunteer_user_id)
    #Initialize variables
    @volunteer_user.points = 0
    @volunteer_user.rev_count = 0
    #Attempt to save the volunteer user to the database and redirect to their availability page
    if @volunteer_user.save
      volunteer_log_in @volunteer_user
      flash[:success] = "Log in successful"
      @scorecard_id = @volunteer_user.user_scorecard.id
      redirect_to edit_availability_path(@volunteer_user.id)
    #If save is unsuccessful, display warning and render form again
    else
      flash.now[:danger] = "Please check the fields carefully"
      render 'new'
    end
  end
  
  def update
    #Find the volunteer user in the database
    @volunteer_user = VolunteerUser.find(params[:id])
    #Try to save the changed profile information and redirect to the user's profile page
    if @volunteer_user.update_attributes(volunteer_user_params)
      @volunteer_user = volunteer_user_params
      redirect_to @volunteer_user
    #If the save is unsuccessful, display warning and render form again
    else
      flash.now[:danger] = "Please check the fields carefully"
      render 'edit'
    end
  end
  
  def edit
    #Find the volunteer user in the database
    @volunteer_user = VolunteerUser.find(params[:id])
    #If a user is not logged in with the id of the user they're trying to edit, redirect to home page
    if !users_id_is(@volunteer_user.id)
      redirect_to root_url
    end
  end
  
  def show
    #Find the volunteer user in the database
    @volunteer_user = VolunteerUser.find(params[:id])
  end
  
  def signal_interest()
    @volunteer_user = VolunteerUser.find(params[:id])
    ru = RequestUser.find(params[:rid])
    if (requesters_id_is(ru.id))
      @volunteer_user.notifications
        .create(title: "#{ru.display_name} is interested in you!", 
        description: "<%= link_to \"See their page here!\", \"#{request_users_url}/#{params[:rid]}\" %>")
      flash[:success] = "This user has been notified!"
      redirect_to @volunteer_user
    end
  end
  
  def following
    if (!current_volunteer_user)
      redirect_to root_url
    end
    @volunteer_user = current_volunteer_user
  end
  
  private
  
    def volunteer_user_params
      #Parameter validation
      params.require(:volunteer_user).permit(:email, :request_post_job_id, :display_name, :zip_code,
                                             :about_me, :points, :rev_count, :no_search, :password, 
                                             :password_confirmation, :avatar, skill_ids: [])
    end
end

app/helpers/volunteer_users_helper.rb
module VolunteerUsersHelper
end

app/views/volunteer_users/edit.html.erb
<% provide(:title, "Edit user") %>
  <h1>Update your profile</h1>

  <section class="container-section">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @volunteer_user, html: { multipart: true } do |f| %>
        <%= render 'shared/vol_error_messages' %>

                <%= f.label :avatar, "Profile Picture" %>
                  <%= f.file_field :avatar %>

          <%= f.label :display_name %>
            <%= f.text_field :display_name, class: 'form-control' %>

              <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control' %>

                  <%= f.label :zip_code, "Zip Code" %>
                    <%= f.text_field :zip_code, class: 'form-control' %>

                      <%= f.label :about_me %>
                        <%= f.text_field :about_me, class: 'form-control' %>

                      <section class="container-skills">
                        <h3>Skills: </h3>
                        <%= f.collection_check_boxes :skill_ids, Skill.order(:title), :id, :title do |b| %>
                                <div class="collection-check-box">
                                <%= b.check_box %>
                                <%= b.label %>
                                </div>
                                <% end %>
                      </section>

                          <%= f.label :password %>
                            <%= f.password_field :password, class: 'form-control' %>

                              <%= f.label :password_confirmation, "Confirmation" %>
                                <%= f.password_field :password_confirmation, class: 'form-control' %>

                                  <%= f.label :no_search, "Hide me from user searches" %>
                                    <%= f.check_box :no_search %>

                                      <%= f.submit "Save changes", class: "btn btn-primary" %>
                                        <% end %>

    </div>
  </div>
  </section>

app/views/volunteer_users/following.html.erb
<center>
    <h1>
    </h1>
</center>

<section class="container-section">

        Followed Events:
        <% for rels in Relationship.all.select{|x| x.follower_id == current_volunteer_user.id} %>
            <div class = "notification">
                <% jobs = RequestPost.all.select{|x| x.request_user_id == rels.followed_id} %>
                <% req_name = RequestUser.find(rels.followed_id).display_name %>
                <h1><%= link_to req_name, RequestUser.find(rels.followed_id) %></h1>
                <% for job in jobs.take(20) %>
                      <%= job.title.truncate(25) %> -- <%= job.description.truncate(25) %> --
                    <%= link_to "<click me!>", job %> <br>
                <% end %>    
            </div>
        <% end %>
</section>

app/views/volunteer_users/index.html.erb
<head>
<style>
input[type=text] {
    width: 130px;
    box-sizing: border-box;
    border: 2px solid #ccc;
    border-radius: 4px;
    font-size: 16px;
    background-color: white;
    background-image: url('/assets/searchicon.png');
    background-position: 10px 10px;
    background-repeat: no-repeat;
    padding: 12px 20px 12px 40px;
    -webkit-transition: width 0.4s ease-in-out;
    transition: width 0.4s ease-in-out;
}

input[type=text]:focus {
    width: 100%;
}
</style>
</head>

<% provide(:title, 'Search Volunteers') %>
  <h1>Search for Volunteers</h1>
  <section class="container-section">
    <%= form_tag volusers_path, :method => 'get' do %>
      <p>
        <%= text_field_tag :search, params[:search] %><br>
          <%= submit_tag "Search", :name => nil %>
      </p>
      <% end %>

        <ul class="volunteer_users">
          <% @volunteer_users.each do |user| %>
            <li>
              <%= link_to user.display_name, user %>
                            <table>
            <% if user.availability %>
                <body>
                    <table border="1">
                        <tr>
                            <th>Monday</th>
                            <th>Tuesday</th>
                            <th>Wednesday</th>
                            <th>Thursday</th>
                            <th>Friday</th>
                            <th>Saturday</th>
                            <th>Sunday</th>
                        </tr>
                        <tr>
                            <td>
                                <% if (!user.availability.mon_st) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= user.availability.mon_st.strftime("%I:%M %p") %>
                                <% end %>
                            
                             - 
                            
                                <% if (!user.availability.mon_en) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= user.availability.mon_en.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                            <td>
                                <% if (!user.availability.tues_st) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= user.availability.tues_st.strftime("%I:%M %p") %>
                                <% end %>
                                
                                 - 
                            
                                <% if (!user.availability.tues_en) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= user.availability.tues_en.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                            <td>
                                <% if (!user.availability.wed_st) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= user.availability.wed_st.strftime("%I:%M %p") %>
                                <% end %>

                                   - 

                                <% if (!user.availability.wed_en) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= user.availability.wed_en.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                      
                            <td>
                                <% if (user.availability.thur_st.nil?) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= user.availability.thur_st.strftime("%I:%M %p") %>
                                <% end %>
                                
                                 - 
                                 
                                <% if (user.availability.thur_en.nil?) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= user.availability.thur_en.strftime("%I:%M %p") %>
                                <% end %>
                     
                            <td>
                                <% if (!user.availability.fri_st) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= user.availability.fri_st.strftime("%I:%M %p") %>
                                <% end %>
                       
                                 - 
                       
                                <% if (!user.availability.fri_en) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= user.availability.fri_en.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                  
                            <td>
                                <% if (!user.availability.sat_st) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= user.availability.sat_st.strftime("%I:%M %p") %>
                                <% end %>
                                
                                 - 
                        
                                <% if (!user.availability.sat_en) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= user.availability.sat_en.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                  
                            <td>
                                <% if (!user.availability.sun_st) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= user.availability.sun_st.strftime("%I:%M %p") %>
                                <% end %>
                                
                                 - 
                       
                                <% if (!user.availability.sun_en) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= user.availability.sun_en.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                      </tr>
                    </table>
                </body>
            <% end %>
            </table>
            </li>
            <% end %>
        </ul>
  </section>

app/views/volunteer_users/new.html.erb
<h1>Volunteer Sign Up</h1>
<section class= "container-section">
<p1>
  <%= link_to "Already have an account? Sign in here", vollogin_path %>
</p1>
<p>
  <%= form_for @volunteer_user, html: { multipart: true } do |f| %>
    <%= render 'shared/vol_error_messages' %>

      <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>

          <%= f.label :display_name, "Display Name" %>
            <%= f.text_field :display_name, class: 'form-control' %>

              <%= f.label :zip_code, "Zip Code" %>
                <%= f.text_field :zip_code, class: 'form-control' %>

                  <%= f.label :about_me, "About Me" %>
                    <%= f.text_area :about_me, class: 'form-control' %>
                    
                                    <%= f.label :avatar, "Profile Picture" %>
                  <%= f.file_field :avatar %>

                      <section class="container-skills">
                        <h3>Skills: </h3>
                        <%= f.collection_check_boxes :skill_ids, Skill.order(:title), :id, :title do |b| %>
                                <div class="collection-check-box">
                                <%= b.check_box %>
                                <%= b.label %>
                                </div>
                                <% end %>
                      </section>

                      <%= f.label :password %>
                        <%= f.password_field :password, class: 'form-control' %>

                          <%= f.label :password_confirmation, "Confirm" %>
                            <%= f.password_field :password_confirmation, class: 'form-control' %>

                              <%= f.label :no_search, "Hide me from user searches" %>
                                <%= f.check_box :no_search %>

                                  <%= f.submit "Create account" %>

                                    <% end %>
</p>
</section>

app/views/volunteer_users/score.html.erb
    <h1>Volunteer Review</h1>
    <section class = "container-section">
    <p>
        <%= form_for UserScorecard.find_by(id: params[:volunteer_user_id]) do |f| %>
            <%= f.hidden_field :volunteer_user_id %>
            <%= hidden_field_tag(:rpjid, params[:rpjid]) %>
            
            <%= f.label :skill_proficiency, "Skill Proficiency" %>
            <%= f.text_field :skill_proficiency %><br>
            
            <%= f.label :attitude, "Attitude" %>
            <%= f.text_field :attitude %><br>
            
            <%= f.label :enthusiasm, "Enthusiasm" %>
            <%= f.text_field :enthusiasm %><br>
            
            <%= f.label :reliability, "Reliability" %>
            <%= f.text_field :reliability %><br>
            
            <%= f.submit "Confirm Review" %>
        <% end %>
    </p>
    </section>

app/views/volunteer_users/show.html.erb
<div align="right">
    <% if ((cuser = current_request_user) != nil) %>
        <%= link_to "<Notify this user you are interested in them!>", {:controller => :volunteer_users, :action => :signal_interest, :rid => cuser.id}, method: :post  %>
            <% end %>
</div>

<h1>
    <%= image_tag @volunteer_user.avatar.url %>
        <%= @volunteer_user.display_name %>
</h1>

<div class="VolunteerInfo">
    <section class="container-section">

        <section class="section-left">

            <p>
                <%= render 'shared/vol_stats' %>
            </p>

            <p>Email:
                <%= @volunteer_user.email %>
            </p>
            <p>Zip Code:
                <%= @volunteer_user.zip_code %>
            </p>
            <p>Review Count:
                <%= @volunteer_user.rev_count %>
            </p>
            <p>Points:
                <%= @volunteer_user.points %>
            </p>
        </section>

        <section class="section-right">

            <h3>About Me</h3>
            <p>
                <%= @volunteer_user.about_me %>
            </p>
            <% if @volunteer_user.skills.any? %>
                <p>Skills:
                    <%= render @volunteer_user.skills %>
                </p>
                <% end %>


        </section>
    </section>
</div>

<p><br /></p>
<p><br /></p>

<div class="VolunteerScore">
    <section class="container-section">

        <section class="section-left">

            <h3>Scorecard</h3>
            <table class = "table-scorecard">
                <tr>
            <th>Skill Proficiency</th>
            <td>
                <%= @volunteer_user.user_scorecard.skill_proficiency %>
            </td>
            </tr>
            <tr>
            <th>Attitude</th>
            <td>
                <%= @volunteer_user.user_scorecard.attitude %>
            </td>
            </tr>
            <tr>
            <th>Enthusiasm</th>
                <td>
                <%= @volunteer_user.user_scorecard.enthusiasm %>
            </td>
            </tr>
            <tr>
            <th>Reliability</th>
            <td>
                <%= @volunteer_user.user_scorecard.reliability %>
            </td>
            </tr>
            </table>
        </section>

        <section class="section-right">
            <h3>Availability</h3>
            
            <table>
            <% if @volunteer_user.availability %>
                <body>
                    <table border="1">
                        <tr>
                            <th> Monday </th>
                            <td>
                                <% if (!@volunteer_user.availability.mon_st) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= @volunteer_user.availability.mon_st.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                            <td>
                                <% if (!@volunteer_user.availability.mon_en) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= @volunteer_user.availability.mon_en.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                        </tr>
                        <tr>
                            <th>Tuesday</th>
                            <td>
                                <% if (!@volunteer_user.availability.tues_st) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= @volunteer_user.availability.tues_st.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                            <td>
                                <% if (!@volunteer_user.availability.tues_en) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= @volunteer_user.availability.tues_en.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                        </tr>
                        <tr>
                            <th>Wednesday</th>
                            <td>
                                <% if (!@volunteer_user.availability.wed_st) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= @volunteer_user.availability.wed_st.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                            <td>
                                <% if (!@volunteer_user.availability.wed_en) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= @volunteer_user.availability.wed_en.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                        </tr>
                        <tr>
                            <th>Thursday</th>
                            <td>
                                <% if (@volunteer_user.availability.thur_st.nil?) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= @volunteer_user.availability.thur_st.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                            <td>
                                <% if (@volunteer_user.availability.thur_en.nil?) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= @volunteer_user.availability.thur_en.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                        </tr>
                        <tr>
                            <th>Friday</th>
                            <td>
                                <% if (!@volunteer_user.availability.fri_st) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= @volunteer_user.availability.fri_st.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                            <td>
                                <% if (!@volunteer_user.availability.fri_en) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= @volunteer_user.availability.fri_en.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                        </tr>
                        <tr>
                            <th>Saturday</th>
                            <td>
                                <% if (!@volunteer_user.availability.sat_st) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= @volunteer_user.availability.sat_st.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                            <td>
                                <% if (!@volunteer_user.availability.sat_en) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= @volunteer_user.availability.sat_en.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                        </tr>
                        <tr>
                            <th>Sunday</th>
                            <td>
                                <% if (!@volunteer_user.availability.sun_st) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= @volunteer_user.availability.sun_st.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                            <td>
                                <% if (!@volunteer_user.availability.sun_en) %>
                                    <%= "Unavailable" %>
                                <% else %>
                                    <%= @volunteer_user.availability.sun_en.strftime("%I:%M %p") %>
                                <% end %>
                            </td>
                        </tr>
                    </table>
                </body>
            <% end %>
            </table>
            <p>
                <%= link_to "Edit availability", edit_availability_path %>
            </p>
        </section>

    </section>
</div>